### ISSUE TITLE
Does this gem works on interface?

### ISSUE THREAD

**Issue by sasharevzin** [RenoFi/graphql-pagination#137]
**Describe the bug**
When I tried to use `.collection_type` on the interface, I got:

```
undefined method `collection_type' for Types::Interfaces::ListingInterface:Module
Did you mean?  connection_type
```

**To Reproduce**
Create interface and return with `.collection_type`

**Expected behavior**
It will paginate

**Mutation/Query**
```
{
  rentals {
    collection {
      id
    }
    metadata {
      totalPages
    }
  }
}
```

**Comment by knapo** [comment]
It does not, but happy to see a PR implementing this!
