### ISSUE TITLE
Upgraded graphql-ruby from 2.4.4 to 2.4.7 - Getting uninitialized constant GraphQL::Schema::Object

### ISSUE THREAD

**Issue by janosrusiczki** [RenoFi/graphql-pagination#183]
**Describe the bug**

The bug is basically in the title and I described it in detail here - https://github.com/rmosolgo/graphql-ruby/issues/5188

Since yesterday when I logged the bug above I discovered that if I remove the `graphql-pagination` gem from my project the error goes away.

Also I noticed that right now your build at https://github.com/RenoFi/graphql-pagination/pull/182 does not pass.

Will revert `graphql-ruby` for the moment and keep an eye out on what is going on here.

**Comment by janosrusiczki** [comment]
PS. Actually for me, removing [line 3 from lib/graphql_pagination.rb](https://github.com/RenoFi/graphql-pagination/blob/main/lib/graphql_pagination.rb#L3) worked but your mileage may vary. :smile:

**Comment by janosrusiczki** [comment]
Fixed by https://github.com/RenoFi/graphql-pagination/pull/182 and https://github.com/RenoFi/graphql-pagination/pull/184.

**Comment by knapo** [comment]
Thanks for reporting @janosrusiczki. The issue is fixed and a new version is released.

**Comment by janosrusiczki** [comment]
@knapo FYI there was some further discussion on [the bug I logged on the graphql-ruby repo](https://github.com/rmosolgo/graphql-ruby/issues/5188) which might be of interest to you.

**Comment by knapo** [comment]
thanks @janosrusiczki !
